version: '3.8'

# 本番環境（Swarm）専用のボリューム保存先指定
volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/glusterfs/swarm-vol/minio
  nextcloud_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/glusterfs/swarm-vol/nextcloud_config
  nextcloud_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/glusterfs/swarm-vol/nextcloud_db
  immich_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/glusterfs/swarm-vol/immich_app
  immich_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/glusterfs/swarm-vol/immich_db
